from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
driver.find_element_by_css_selector("[title='Selenium Ruby']").click()
driver.find_element_by_css_selector(".reviews_tab>a").click()
driver.find_element_by_class_name("star-5").click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
name = driver.find_element_by_id("author")
name.send_keys("Larry")
email = driver.find_element_by_id("email")
email.send_keys("larry_jons@ex.com")
driver.find_element_by_id("submit").click()
driver.quit()